ERP System/Controllers/DiscountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataLayer;
using DataLayer.Models;
using DataLayer.ViewModels;
using DataLayer.Utils;
using ERP_System.Utils;

namespace ERP_System.Controllers
{
    [CheckSession]
    public class DiscountController : Controller
    {
        DbConnector db = new DbConnector();
        // GET: UnitMaster
        [RBAC(AccessType = 2)]
        public ActionResult Index(int? id,string ErrorMsg)
        {
            DiscountViewModel model = new DiscountViewModel();
            if (model.DiscountTypeList == null)
            {
                model.DiscountTypeList = db.GetDsicountList();
            }
            if (id.HasValue)
            {
                model.Discount = db.GetDiscountById(id.Value);
            }
            else
            {
                model.Discount = new Discount();
            }
            if (!string.IsNullOrEmpty(ErrorMsg))
            {
                ViewBag.ErrorMsg = ErrorMsg;
            }
            return View(model);
        }

        [RBAC(AccessType = 0)]
        [HttpPost]
        public ActionResult Create(Discount discount)
        {
            db.SaveDiscount(discount);
            return RedirectToAction("Index");
        }

        [RBAC(AccessType = 3)]
        public ActionResult Delete(int id)
        {
            Discount Discount = db.Discounts.Find(id);
            if (Discount == null)
            {
                return HttpNotFound();
            }
            else
            {
                if (db.DeleteDiscount(Discount))
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Index", new { ErrorMsg = MessageStore.DeleteError });
        }

        [HttpPost]
        public JsonResult ExistingDiscountCode(string DiscountCode)
        {
            var Discounts = db.Discounts.Where(x => x.DiscountCode == DiscountCode).FirstOrDefault();
            if (Discounts == null)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ExistingPromoCode(string PromoCode)
        {
            var Discounts = db.Discounts.Where(x => x.PromoCode == PromoCode).FirstOrDefault();
            if (Discounts == null)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            return Json(true, JsonRequestBehavior.AllowGet);
        }
    }
}

ERP System/Controllers/LedgerController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using DataLayer.Models;
using DataLayer.Utils;
using DataLayer;
using DataLayer.ViewModels;
using ERP_System.Utils;
using System;

namespace ERP_System.Controllers
{
    [CheckSession]
    public class LedgerController : Controller
    {
        DbConnector db = new DbConnector();

        // GET: Ledger
        [RBAC(AccessType = 2)]
        public ActionResult Index(string ErrorMsg,string Type)
        {
            LedgerViewModel model = new LedgerViewModel();
            if (string.IsNullOrEmpty(Type))
            {                
                model.Type = Enums.RecordType.Supplier.ToString();
                model.LedgerList = db.GetLedgerListByType(model.Type);
            }
            else
            {
                if (Type == "Other")
                {
                    model.LedgerList = db.LedgerListOfOther();
                }
                else
                {
                    model.LedgerList = db.GetLedgerListByType(Type);
                }
            }
            if (!string.IsNullOrEmpty(ErrorMsg))
            {
                ViewBag.ErrorMsg = ErrorMsg;
            }
            return View(model);
        }

        public ActionResult Create(int? id)
        {
            Ledger ledger = null;
            if (id.HasValue && id.Value > 0)
            {
                ledger = PurchaseCalculator.GetLedgerOeningBalance(id.Value); 
                if(ledger.Contact == null)
                {
                    ledger.Contact = new Contact();
                }
                ledger.ContactCategoryList = DropdownManager.GetContactCategoryList(null);
                ledger.ContactSubCategoryList = DropdownManager.GetContactSubCategoryList(ledger.AccountCategoryId);
                Voucher voucher = db.Vouchers.Where(x => x.LedgerId == id.Value && x.VoucherFor == Constants.OPENING_BALANCE && x.CompanyId == db.CompanyId).FirstOrDefault();
                if(voucher != null)
                {
                    ledger.StartingBalance = voucher.Total;
                    ledger.EntryDate = voucher.EntryDate;
                }
                else
                {
                    ledger.StartingBalance = 0;
                    ledger.EntryDate = DateTime.Now;
                }
            }
            else
            {
                ledger = new Ledger();
                ledger.Contact = new Contact();
                ledger.ContactCategoryList = DropdownManager.GetContactCategoryList(null);
                ledger.ContactSubCategoryList = DropdownManager.GetContactSubCategoryList(null);
                ledger.EntryDate = DateTime.Now;
            }
            return View(ledger);
        }

        [RBAC(AccessType = 0)]
        [HttpPost]
        public ActionResult Create(Ledger ledger)
        {
            if (!string.IsNullOrEmpty(ledger.other))
            {
                ledger.AccountCategoryId = 0;
                ledger.AccountCategoryId = db.GetContactCategoryIdByName(ledger.other);
            }
            if(ledger.AccountSubCategoryId==-1)
            {
                ledger.AccountSubCategoryId = null;
            }
          
            if(ledger.AccountCategoryId == 1 || ledger.AccountCategoryId == 47)
            {
                ledger.LedgerType = Constants.LEDGER_TYPE_PAYMENTTYPE;
            }
            IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
            if (ModelState.IsValid)
            {
                if (db.SaveLedger(ledger))
                {
                    Voucher Voucher = db.Vouchers.Where(x => x.LedgerId == ledger.LedgerId && x.VoucherFor == Constants.OPENING_BALANCE && x.CompanyId == db.CompanyId).FirstOrDefault();
                    if (Voucher != null)
                    {
                        Voucher.Type = ledger.Type;
                        Voucher.Total = ledger.StartingBalance;
                        Voucher.EntryDate = ledger.EntryDate ?? DateTime.Now;
                        db.SaveVauchers(Voucher);
                    }
                    else
                    {
                        Voucher = new Voucher();
                        Voucher.LedgerId = ledger.LedgerId;
                        Voucher.Total = ledger.StartingBalance;
                        Voucher.Type = ledger.Type;
                        Voucher.VoucherFor = Constants.OPENING_BALANCE;
                        Voucher.Particulars = Constants.OPENING_BALANCE;
                        Voucher.EntryDate = ledger.EntryDate ?? DateTime.Now;
                        db.SaveVauchers(Voucher);
                    }
                    return RedirectToAction("Index", new { Type = ledger.Contact.Type });
                }
            }
            return View(ledger);
        }

        public JsonResult GetLedgerList(string term)
        {
            var result = new List<KeyValuePair<string, string>>();
            IList<SelectListItem> List = DropdownManager.GetLedgerSelectList();
            foreach (var item in List)
            {
                result.Add(new KeyValuePair<string, string>(item.Value.ToString(), item.Text));
            }
            var result3 = result.Where(s => s.Value.ToLower().Contains(term.ToLower())).Select(w => w).ToList();
            return Json(result3, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult SaveNewContact(string othercontact)
        {
            AccountCategory contactcategory = new AccountCategory();
            contactcategory.Name = othercontact;
            if (db.SaveContactcategory(contactcategory))
            {
                return Json(true);
            }
            else
            {
                return Json(false);
            }
        }
        
        [HttpPost]
        public ActionResult SaveContactCategory(ContactCategoryViewModel model)
        {
            db.SaveContactcategory(model.ContactCategory);
            return RedirectToAction("CreateContactCategory");
        }

        public ActionResult CreateContactCategory(int? id)
        {
            ContactCategoryViewModel model = new ContactCategoryViewModel();
            if (model.ContactCategoryList == null)
            {
                model.ContactCategoryList = db.GetContactCategoryList(null);
            }
            if (id.HasValue)
            {
                model.ContactCategory = db.GetContactCategoryById(id.Value);
            }
            else
            {
                model.ContactCategory = new AccountCategory();
            }
            return View(model);
        }

        public ActionResult CreateContactSubCategory(int? id)
        {
            ContactCategoryViewModel model = new ContactCategoryViewModel();
            if (model.ContactSubCategoryList == null)
            {
                model.ContactCategoryList = db.GetContactCategoryList(0);
            }
            if (id.HasValue)
            {
                model.ContactCategory = db.GetContactCategoryById(id.Value);
            }
            else
            {
                model.ContactCategory = new AccountCategory();
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult CreateContactSubCategory(AccountSubCategory model)
        {
            db.SaveContactSubCategory(model);
            return View(model);
        }

        [HttpPost]
        public JsonResult ContactSubCategoryList(int contactcategoryid)
        {
            List<AccountSubCategory> sublist = db.GetContactSubCategoryList(contactcategoryid);
            List<SelectListItem> itemList = new List<SelectListItem>();
            if (sublist != null && sublist.Count > 0)
            {
                foreach (var item in sublist)
                {
                    itemList.Add(new SelectListItem() { Text = item.ContactSubCategoryName, Value = item.AccountSubCategoryId.ToString() });
                }
            }
            return Json(new SelectList(itemList, "Value", "Text"));
        }

        public ActionResult Delete(int id)
        {
            string Type = null;
            Ledger ledger = db.Ledgers.Where(x => x.LedgerId == id).FirstOrDefault();
            if (db.DeleteLedger(ledger))
            {
                return RedirectToAction("Index", new { Type = Type });
            }
            return RedirectToAction("Index", new { ErrorMsg = MessageStore.DeleteError , Type  = Type });
        }

        [HttpPost]
        public ActionResult _LedgerList(string Type)
        {
            LedgerViewModel model = new LedgerViewModel();
            if(Type == "Other")
            {
                model.LedgerList = db.LedgerListOfOther();
            }
            else
            {
                model.LedgerList = db.GetLedgerListByType(Type);
            }
            model.Type = Type;
            return PartialView(model);
        }

        [HttpPost]
        public JsonResult ExistingLedger(string Name)
        {
            var Ledger = db.Ledgers.Where(x => (x.Name == Name && x.CompanyId == null) || (x.Name == Name && x.CompanyId == db.CompanyId)).FirstOrDefault();
            if (Ledger == null)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            return Json(true, JsonRequestBehavior.AllowGet);
        }
    }
}

ERP System/Views/Shared/_Discount.cshtml
@model DataLayer.ViewModels.PurchaseInvoiceItemViewModel
@{
    ViewBag.Title = "_Discount";
}

@using (Ajax.BeginForm("AddDiscount", "Home", new AjaxOptions { HttpMethod = "POST", OnSuccess = "DiscountResultList(data);", OnFailure = "error(data);" }))
{
    @Html.HiddenFor(model => model.Discount.SKUMaster.SKUMasterId, new { @id = "skuId" })
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Sale Discount</h4>
            </div>
            <div class="modal-body">
                <div class="col-lg-12">
                    <p><b>Add new discount for selected SKU or check discount from list</b></p>
                    <div class="col-lg-4">
                        <label for="exampleInputEmail1" class="erplabel">SKU</label>
                        @Html.EditorFor(model => model.Discount.SKUMaster.SKU, new { htmlAttributes = new { @class = "form-control", @Readonly = "true", @id = "ModelSKU" } })
                        @Html.ValidationMessageFor(model => model.Discount.SKUMaster.SKU, "Required", new { @class = "text-danger" })                       
                    </div>
                    <div class="clearfix"></div>
                    <br />
                    <p><b>Add New</b></p>
                    <div class="col-lg-4">
                        <label for="exampleInputEmail1" class="erplabel">Discount Code</label>
                        @Html.EditorFor(model => model.Discount.DiscountCode, new { htmlAttributes = new { @class = "form-control", @id = "ModelDiscountCode", @autocomplete = "off" } })
                        @Html.ValidationMessageFor(model => model.Discount.DiscountCode, "Required", new { @class = "text-danger" })
                        <label id="ERR_DiscountCode" style="color: rgb(169, 68, 66); font-weight: normal; display: inline-block;"></label> 
                    </div>
                    <div class="col-lg-4">
                        <label for="exampleInputEmail1" class="erplabel">Discount (%)</label>
                        @Html.EditorFor(model => model.Discount.DiscountPercent, new { htmlAttributes = new { @class = "form-control", @id = "ModelDiscountPercent", @autocomplete = "off" } }) 
                        @Html.ValidationMessageFor(model => model.Discount.DiscountPercent, "Required", new { @class = "text-danger" })
                    </div>
                    <div class="col-lg-4">
                        <label for="exampleInputEmail1" class="erplabel">Max Discount Allowed</label>
                        @Html.EditorFor(model => model.Discount.MaxDiscountAllowed, new { htmlAttributes = new { @class = "form-control", @id = "ModelDiscountMax", @autocomplete = "off" } })
                        @Html.ValidationMessageFor(model => model.Discount.MaxDiscountAllowed, "Required", new { @class = "text-danger" })
                    </div>
                    <div class="clearfix"></div>
                    <br />
                    <p><b>Select Discount</b></p>
                    <div class="col-lg-12">
                        @if (Model.Discount.DiscountList.Count > 0)
                        {
                            <div style="overflow-y:auto;height:300px;">
                                <h5 class="header">Applicable Discounts on this SKU</h5>
                                <table class="table table-responsive">
                                    <thead>
                                        <tr>
                                            <th>
                                                Code
                                            </th>
                                            <th>
                                                Discount Percent
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody id="DiscountTable">
                                        @for (int i = 0; i < Model.Discount.DiscountList.Count; i++)
                                        {
                                            <tr>
                                                <td>
                                                    <div class="form-group">
                                                        @Html.HiddenFor(q => Model.Discount.DiscountList[i].DiscountId)
                                                        @Html.CheckBoxFor(q => Model.Discount.DiscountList[i].IsSelected, new { @id = "DiscountCheckList" + Model.Discount.DiscountList[i].DiscountId })
                                                        <label for="exampleInputEmail1" class="erplabel">@Model.Discount.DiscountList[i].Code</label>
                                                    </div>
                                                </td>
                                                <td>
                                                    <div class="form-group">
                                                        <label for="exampleInputEmail1" class="erplabel">@Model.Discount.DiscountList[i].DiscountPercent</label> %
                                                    </div>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        }
                        else
                        {
                            <div class="clearfix"></div>
                                <br />
                                <p class="erplabel">No Discount Available</p>
                        }

                    </div>
                    <div class="clearfix"></div>
                    <br />
                </div>
                <div class="modal-footer" style="border-top:none !important;">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary" id="ModelDiscountSubmit">Save</button>
                </div>
            </div>
        </div>
    </div>
}
@*<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery-2.2.3.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>*@
<script type="text/javascript">
    $(document).ready(function () {
        $("#ModelDiscountCode").on("change keyup paste", function () {
            var DiscountCode = $('#ModelDiscountCode').val();
            var serviceURL = '@Url.Action("ExistingDiscountCode", "Discount")?DiscountCode=' + DiscountCode;
            $.ajax({
                type: "POST",
                url: serviceURL,
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: successFunc,
            });
            function successFunc(data) {
                if (data == true) {
                    $("#ModelDiscountSubmit").prop("disabled", true);
                    $("#ERR_DiscountCode").text("Discount Code Already Exist");
                }
                else {
                    $('#ModelDiscountSubmit').prop("disabled", false);
                    $("#ERR_DiscountCode").text(null);
                }
            }
        })

        $("#ModelDiscountPercent,#ModelDiscountMax").keypress(function (e) {
            if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57) && e.which != 46) {
                return false;
            }
        });
    });
</script>