ERP System/Controllers/StoreMasteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataLayer;
using DataLayer.Models;
using DataLayer.ViewModels;
using DataLayer.Utils;
using ERP_System.Utils;

namespace ERP_System.Controllers
{
    [CheckSession]
    public class StoreMasteController : Controller
    {
        DbConnector db = new DbConnector();
        // GET: UnitMaster
        [RBAC(AccessType = 2)]
        public ActionResult Index(int? id,string  ErrorMsg)
        {
            StoreMasteModel model = new StoreMasteModel();
            if (model.StoreLists == null)
            {
                model.StoreLists = db.GetStoreListList();
            }
            if (id.HasValue)
            {
                model.Store = db.GetStoreById(id.Value);
            }
            else
            {
                model.Store = new StoreMaste();
            }
            if (!string.IsNullOrEmpty(ErrorMsg))
            {
                ViewBag.ErrorMsg = ErrorMsg;
            }
            return View(model);
        }

        [RBAC(AccessType = 0)]
        [HttpPost]
        public ActionResult Create(StoreMaste store)
        {
            db.SaveStore(store);
            return RedirectToAction("Index");
        }

        [RBAC(AccessType = 3)]
        public ActionResult Delete(int id)
        {
            StoreMaste store = db.Stores.Find(id);
            db.DeleteStore(store);
            if (store == null)
            {
                return HttpNotFound();
            }
            else
            {
                if (db.DeleteStore(store))
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Index", new { ErrorMsg = MessageStore.DeleteError });
        }
    }
}

ERP System/Views/StoreMaste/Index.cshtml
@model DataLayer.ViewModels.StoreMasteModel

@{
    ViewBag.Title = "";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/jquery-2.2.3.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/state.js" type="text/javascript"></script>
<script>
    $(document).ready(function () {

        if ($("#hiddenStoreMasteId").val() != 0) {
            $("#btnSubmit").text("Update");
        }
        else {
            $("#btnSubmit").text("Save");
        }
        var stat = $("#state").val();
        var City = $("#City").val();
        $("#listBox option").filter(function () {
            if ($(this).val() == stat) {
                selct_district(this.value);
                return true;
            }
        }).prop('selected', true);
        $("#secondlist option").filter(function () {
            if ($(this).val() == City) {
                return true;
            }
        }).prop('selected', true);

        $("#btnSubmit").click(function () {
            var POB2 = $("#listBox1").val();
            document.getElementById('state').value = POB2;

            var POB1 = $("#secondlist").val();
            document.getElementById('City').value = POB1;
        });

        $("#Landline").keypress(function (e) {
            if (e.which != 8 && e.which != 0 && (e.which < 48 || e.which > 57)) {
                return false;
            }
        });
    })
</script>    
<script src="~/Scripts/state.js" type="text/javascript"></script>
<section class="content-header">
    <h1> Store <small>panel</small> </h1>
    <label id="ErrLabel" style="color:red"></label>
    <ol class="breadcrumb">
        <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Store</li>
    </ol>
</section>
<!-- Main content -->
<section class="content">
    <!-- Small boxes (Stat box) -->
    <div class="row">
        <div class="col-md-4 col-lg-4 col-xs-12 col-sm-4">
            <div class="box box-primary" style="height:450px">
                <div class="box-header with-border">
                    <h3 class="box-title">Store Details</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">

                    @if (!string.IsNullOrEmpty(ViewBag.ErrorMsg))
                    {
                        <script type="text/javascript">
                            $("#ErrLabel").text("@ViewBag.ErrorMsg");
                            setTimeout(function () {
                                $('#ErrLabel').fadeOut();
                            }, 5000);
                        </script>
                    }
                    else
                    {
                        <script type="text/javascript">
                            $("#ErrLabel").hide();

                        </script>
                    }
                    <!-- /.box-header -->
                    <!-- form start  <p class="help-block">Example block-level help text here.</p>-->
                    @using (Html.BeginForm("Create", "StoreMaste", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.HiddenFor(model => model.Store.StoreMasteId,new { @id= "hiddenStoreMasteId" })

                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 nopadding">
                            <div class="form-group">
                                <label for="exampleInputEmail1" class="erplabel">Store Name</label>
                                @Html.EditorFor(model => model.Store.StoreName, new { htmlAttributes = new { @class = "form-control", @id = "txtSize" } })
                                @Html.ValidationMessageFor(model => model.Store.StoreName, "", new { @class = "text-danger" })
                            </div>
                        </div>


                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 nopadding">
                        <div class="form-group">
                            <label for="exampleInputEmail1" class="erplabel">Landline Number</label>
                            @Html.EditorFor(model => model.Store.Landline, new { htmlAttributes = new { @class = "form-control", @id = "Landline" } })
                            @Html.ValidationMessageFor(model => model.Store.Landline, "", new { @class = "text-danger" })
                        </div>
                        </div>

                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 nopadding">
                            <div class="form-group">
                                <label for="exampleInputEmail1" class="erplabel">Address</label>
                                @Html.EditorFor(model => model.Store.Address, new { htmlAttributes = new { @class = "form-control", @id = "txtSize" } })
                                @Html.ValidationMessageFor(model => model.Store.Address, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 nopadding">
                            <div class="form-group">
                                <label for="exampleInputEmail1" class="erplabel">State</label>
                                <select id="listBox1" onchange='selct_district(this.value)' class="form-control"></select>
                                @Html.HiddenFor(model => model.Store.State, new { @id = "state" })
                            </div>
                        </div>

                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 nopadding">
                            <div class="form-group">
                                <label for="exampleInputEmail1" class="erplabel">City</label>
                                <select id="secondlist" class="form-control"></select>
                                @Html.HiddenFor(model => model.Store.City, new { @id = "City" })
                            </div>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 nopadding">
                            <div class="form-group">
                                <label for="exampleInputEmail1" class="erplabel">Email</label>
                                @Html.EditorFor(model => model.Store.Email, new { htmlAttributes = new { @class = "form-control", @id = "txtSize" } })
                                @Html.ValidationMessageFor(model => model.Store.Email, "", new { @class = "text-danger" })
                            </div>
                        </div>
                            <div class="clearfix"></div>
                            <div class="box-footer nopadding">
                                <button type="submit" class="btn btn-bitbucket btn-sm pull-right" id="btnSubmit"><i class="fa fa-save"></i> Save</button>
                            </div>
                            }
                        </div>
            </div>
        </div>
        <div class="col-md-8 col-lg-8 col-xs-12 col-sm-8">
            <div class="box box-primary">
                <div class="box">
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div style="overflow-y:scroll; height:488px;">
                            @if (Model.StoreLists != null && Model.StoreLists.Count > 0)
                            {
                                <table id="example1" class="table table-bordered table-striped">
                                    <thead>
                                        <tr>
                                            <th>Store Name</th>
                                            <th>City</th>
                                            <th>Landline</th>
                                            <th>Email</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.StoreLists)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.StoreName)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.City)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Landline)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Email)
                                                </td>
                                                <td>
                                                    @*<a class="fa fa-pencil fa-2x" href="@Url.Action("Index", "StoreMaste", new { id = item.StoreMasteId })" title="Edit"></a> &nbsp;   <span style="font-size:1.5em;">|</span>  &nbsp;
                                                        <a class="fa fa-trash-o fa-2x" href="@Url.Action("Delete","StoreMaste", new { id = item.StoreMasteId })" onclick="return confirm('Are you sure you want to delete this Store Master?');" title="Delete"></a>*@
                                                    <a href="@Url.Action("Index", "StoreMaste")?id=@item.StoreMasteId">
                                                        Edit
                                                    </a>
                                                    ||
                                                    <a href="@Url.Action("Delete", "StoreMaste",new { id=@item.StoreMasteId})" onclick="return confirm('Are you sure you want to delete this Unit')">
                                                        Delete
                                                    </a>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>

                                </table>
                            }
                            else
                            {
                                <label>@DataLayer.Constants.NO_RECORDS_FOUND</label>
                            }
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
        </div>
        <!-- /.row -->
    </div>
</section>