ERP System/Controllers/SaleReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataLayer;
using DataLayer.Models;
using DataLayer.Utils;
using DataLayer.ViewModels;
using ERP_System.Utils;
using System.IO;

namespace ERP_System.Controllers
{
    [CheckSession]
    public class SaleReportController : Controller
    {
        DbConnector db = new DbConnector();

        [RBAC(AccessType = 2)]
        public ActionResult Index()
        {
            PurchaseReportViewModel model = new PurchaseReportViewModel();
            Ledger SaleLedger = db.Ledgers.Where(x => x.Name == Constants.LEDGER_TYPE_SALE_RETURN_LEDGER).FirstOrDefault();
            if (SaleLedger != null)
            {
                List<Voucher> VoucherList = db.Vouchers.Where(x => x.LedgerId == SaleLedger.LedgerId && x.VoucherFor != Constants.OPENING_BALANCE && x.CompanyId == db.CompanyId).OrderBy(x => x.EntryDate).ToList();
                model = GetReport(VoucherList);
            }
            return View(model);
        }


        [HttpPost]
        public ActionResult _InvoiceList(PurchaseReportViewModel ViewModel)
        {

            Ledger PurchaseLedger = db.Ledgers.Where(x => x.Name == Constants.LEDGER_TYPE_SALE_RETURN_LEDGER).FirstOrDefault();
            if (PurchaseLedger != null)
            {
                List<Voucher> VoucherList = db.Vouchers.Where(x => x.LedgerId == PurchaseLedger.LedgerId && x.VoucherFor != Constants.OPENING_BALANCE && x.CompanyId == db.CompanyId).ToList();

                if (ViewModel.SaleReportType == Enums.SaleReportType.All)
                {
                    VoucherList = db.Vouchers.Where(x => x.LedgerId == PurchaseLedger.LedgerId && x.VoucherFor != Constants.OPENING_BALANCE && x.CompanyId == db.CompanyId).ToList();
                }
                else if (ViewModel.SaleReportType == Enums.SaleReportType.SaleInvoice)
                {
                    VoucherList = db.Vouchers.Where(x => x.LedgerId == PurchaseLedger.LedgerId && (x.VoucherFor == Constants.SALE_TYPE_SALE_INVOICE || x.VoucherFor == Constants.SALE_TYPE_SALE_VOUCHER || x.VoucherFor == Constants.SALE_TYPE_WPS) && x.VoucherFor != Constants.OPENING_BALANCE && x.CompanyId == db.CompanyId).ToList();
                }
                else if (ViewModel.SaleReportType == Enums.SaleReportType.SaleReturn)
                {
                    VoucherList = db.Vouchers.Where(x => x.LedgerId == PurchaseLedger.LedgerId && (x.VoucherFor == Constants.SALE_TYPE_SALE_EXCHANGE || x.VoucherFor == Constants.JOURNAL_ENTRY) && x.VoucherFor != Constants.OPENING_BALANCE && x.CompanyId == db.CompanyId).ToList();
                }

                if (ViewModel.FromDate.HasValue)
                {
                    VoucherList = VoucherList.Where(x => x.EntryDate >= ViewModel.FromDate).OrderBy(x => x.EntryDate).ToList();
                }

                if (ViewModel.ToDate.HasValue)
                {
                    VoucherList = VoucherList.Where(x => x.EntryDate <= ViewModel.ToDate).OrderBy(x => x.EntryDate).ToList();
                }
                ViewModel = GetReport(VoucherList);
            }
            return PartialView(ViewModel);
        }


        public PurchaseReportViewModel GetReport(List<Voucher> VoucherList)
        {
            PurchaseReportViewModel model = new PurchaseReportViewModel();
            model.Company = SessionManager.GetSessionCompany();
            model.Branch = SessionManager.GetSessionBranch();
            List<int?> SaleInvoiceIds = VoucherList.Select(x => x.SaleInvoiceId).ToList();
            List<SaleInvoice> SaleInvoiceList = db.SaleInvoices.Where(x => SaleInvoiceIds.Contains(x.SaleInvoiceId)).ToList();
            foreach (var item in VoucherList)
            {
                PurchaseReportList ReportItem = new PurchaseReportList();
                if (item.VoucherFor == Constants.SALE_TYPE_SALE_INVOICE || item.VoucherFor == Constants.SALE_TYPE_SALE_EXCHANGE || item.VoucherFor == Constants.SALE_TYPE_SALE_VOUCHER || item.VoucherFor == Constants.SALE_TYPE_WPS)
                {
                    SaleInvoice SaleInvoice = SaleInvoiceList.Where(x => x.SaleInvoiceId == item.SaleInvoiceId).FirstOrDefault();
                    if (SaleInvoice != null)
                    {
                        if (item.VoucherFor == Constants.SALE_TYPE_SALE_INVOICE || item.VoucherFor == Constants.SALE_TYPE_SALE_EXCHANGE || item.VoucherFor == Constants.SALE_TYPE_WPS)
                        {
                            ReportItem.NoOfItem = db.SaleInvoiceItems.Where(x => x.SaleInvoiceId == item.SaleInvoiceId && x.Status == Constants.SALE_ITEM_SOLD).Count();
                        }
                        else
                        {
                            ReportItem.NoOfItem = db.ProductVouchers.Where(x => x.SaleInvoiceId == item.SaleInvoiceId).Count();
                        }
                        ReportItem.InvoiceId = item.SaleInvoiceId ?? 0;
                        ReportItem.Type = item.VoucherFor;
                        ReportItem.EntryDate = item.EntryDate;
                        ReportItem.InvoiceNumber = SaleInvoice.SaleInvoiceNo;
                        ReportItem.GrossAmount = SaleInvoice.Subtotal;
                        ReportItem.Adjustment = SaleInvoice.Adjustment ?? 0;
                        ReportItem.TotalTax = SaleInvoice.TotalTax;
                        ReportItem.TotalWithAdjustment = SaleInvoice.TotalWithAdjustment;
                        model.PurchaseReportList.Add(ReportItem);
                    }
                }
                else
                {
                    ReportItem.InvoiceNumber = item.VoucherNumber;
                    ReportItem.Type = item.VoucherFor;
                    ReportItem.EntryDate = item.EntryDate;
                    ReportItem.GrossAmount = -item.Total;
                    ReportItem.Adjustment = 0;
                    ReportItem.TotalTax = 0;
                    ReportItem.TotalWithAdjustment = -item.Total;
                    model.PurchaseReportList.Add(ReportItem);
                }
            }
            model.Subtotal = model.PurchaseReportList.Sum(x => x.GrossAmount);
            model.TotalTax = model.PurchaseReportList.Sum(x => x.TotalTax);
            model.TotalDiscount = model.PurchaseReportList.Sum(x => x.Adjustment);
            model.GrandTotal = model.PurchaseReportList.Sum(x => x.TotalWithAdjustment);
            return model;
        }


        [HttpPost]
        public FileContentResult FileContentResult(PurchaseReportViewModel ViewModel)
        {
            string header = "Sale Report";
            if (ViewModel.FromDate.HasValue)
            {
                header = header + " From " + ViewModel.FromDate.Value.ToString("dd'/'MM'/'yyyy");
            }
            if (ViewModel.ToDate.HasValue)
            {
                header = header + " To " + ViewModel.ToDate.Value.ToString("dd'/'MM'/'yyyy");
            }
            Ledger PurchaseLedger = db.Ledgers.Where(x => x.Name == Constants.LEDGER_TYPE_PURCHASE_RETURN_LEDGER).FirstOrDefault();
            if (PurchaseLedger != null)
            {
                List<Voucher> VoucherList = null;

                if (ViewModel.SaleReportType == Enums.SaleReportType.All)
                {
                    VoucherList = db.Vouchers.Where(x => x.LedgerId == PurchaseLedger.LedgerId && x.VoucherFor != Constants.OPENING_BALANCE && x.CompanyId == db.CompanyId).ToList();
                }
                else if (ViewModel.SaleReportType == Enums.SaleReportType.SaleInvoice)
                {
                    VoucherList = db.Vouchers.Where(x => x.LedgerId == PurchaseLedger.LedgerId && (x.VoucherFor == Constants.SALE_TYPE_SALE_INVOICE || x.VoucherFor == Constants.SALE_TYPE_SALE_VOUCHER || x.VoucherFor == Constants.SALE_TYPE_WPS) && x.VoucherFor != Constants.OPENING_BALANCE && x.CompanyId == db.CompanyId).ToList();
                }
                else if (ViewModel.SaleReportType == Enums.SaleReportType.SaleReturn)
                {
                    VoucherList = db.Vouchers.Where(x => x.LedgerId == PurchaseLedger.LedgerId && (x.VoucherFor == Constants.SALE_TYPE_SALE_EXCHANGE || x.VoucherFor == Constants.JOURNAL_ENTRY) && x.VoucherFor != Constants.OPENING_BALANCE && x.CompanyId == db.CompanyId).ToList();
                }

                if (ViewModel.FromDate.HasValue)
                {
                    VoucherList = VoucherList.Where(x => x.EntryDate >= ViewModel.FromDate).OrderBy(x => x.EntryDate).ToList();
                }

                if (ViewModel.ToDate.HasValue)
                {
                    VoucherList = VoucherList.Where(x => x.EntryDate <= ViewModel.ToDate).OrderBy(x => x.EntryDate).ToList();
                }
                ViewModel = GetReport(VoucherList);
            }

            //var LedgerList = db.GetLedgerList(model);
            StringWriter sw = new StringWriter();

            sw.WriteLine("\"\",\"\",\"\",\"\",\"" + header + "\",\"\",\"\",\"\"");
            sw.WriteLine("\"SR NO.\",\"Invoice Number\",\"Invoicing Date\",\"No. Of Item\",\"Gross Amount\",\"Total tax\",\"Adjustment\",\"Total\",\"Type\"");
            int i = 1;
            foreach (var item in ViewModel.PurchaseReportList)
            {
                sw.WriteLine(string.Format("\"{0}\",\"{1}\",\"{2}\",\"{3}\",\"{4}\",\"{5}\",\"{6}\",\"{7}\",\"{8}\",\"{9}\"", i, item.InvoiceNumber, item.EntryDate.Value.ToString("dd'/'MM'/'yyyy"), item.NoOfItem, item.GrossAmount.ToString("0.00"), item.TotalTax.ToString("0.00"), item.Adjustment.ToString("0.00"), item.TotalWithAdjustment.ToString("0.00"), item.Type, ""));
                i++;
            }

ERP System/Views/SaleReport/Details.cshtml
@model DataLayer.Models.SaleInvoice
@{
    ViewBag.Title = "Sale Report - Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="content" style="min-height: 0px !important;">
    <div class="row">
        <div class="col-md-8 col-lg-8 col-xs-12 col-sm-8">
            <div class="box box-primary">
                <div class="box">
                    <div class="box-body">
                        @if (Model.SaleInvoiceItemList != null)
                        {
                            @Html.HiddenFor(model => model.TotalNotMapped, new { @id = "TotalNotMapped" })
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th class="erplabel"><b>Product Number</b></th>
                                        <th class="erplabel"><b>Quantity</b></th>
                                        <th class="erplabel"><b>MRP</b></th>
                                        <th class="erplabel"><b>Tax</b></th>
                                        <th class="erplabel"><b>Discount</b></th>
                                        <th class="erplabel"><b>Subtotal</b></th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.SaleInvoiceItemList.Where(x => x.Status == DataLayer.Constants.SALE_ITEM_SOLD))
                                    {
                                        <tr>
                                            <td>@item.Product.SerialNumber</td>
                                            <td>@item.Quantity</td>
                                            <td>@item.MRP</td>
                                            <td>@item.ApplicableTaxValue</td>
                                            <td>@item.Discount</td>
                                            <td>@(item.BasicPrice)</td>
                                        </tr>
                                    }
                                    @foreach (var item in Model.SaleInvoiceItemList.Where(x => x.Status == DataLayer.Constants.SALE_ITEM_RETURN))
                                    {
                                        <tr>
                                            <td>@item.Product.SerialNumber</td>
                                            <td>@item.Quantity</td>
                                            <td>@item.MRP</td>
                                            <td>- @item.ApplicableTaxValue</td>
                                            <td>@item.Discount</td>
                                            <td>- @(item.BasicPrice)</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        }
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4 col-lg-4 col-xs-12 col-sm-4">
            <div class="box box-primary">
                <div class="box">
                    <div class="box-body" style="height:380px;">
                        <table class="table">
                            <tr><th>Invoice Number:</th><td>@Model.SaleInvoiceNo</td></tr>
                            <tr><th>Invoicing Date :</th><td>@Model.InvoicingDate.ToString("dd'/'MM'/'yyyy") @Model.Time</td></tr>
                            <tr><th>Subtotal :</th><td>@Model.Subtotal</td></tr>
                            <tr><th>Total Discount :</th><td>@Model.TotalDiscount</td></tr>
                            <tr><th>Total Tax: </th><td>@Model.TotalTax</td></tr>
                            <tr><th>Total : </th><td>@Model.TotalWithAdjustment.ToString("0.00")</td></tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>        
    </div>
</section>

ERP System/Views/SaleReport/Index.cshtml
@model DataLayer.ViewModels.PurchaseReportViewModel
@{
    ViewBag.Title = "Purchase Report - Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section class="content-header">
    <h1> Sale <small>Report</small> </h1>
</section>
<section class="content" style="min-height: 0px !important;">
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-header">
                    <div class="col-lg-2">
                        <div class="form-group">
                            <label class="control-label erplabel" for="email">Type</label>
                            @Html.EnumDropDownListFor(model => model.SaleReportType, "Select a Title", new { @class = "form-control", @required = "required", @id = "SaleReportType" })
                            @Html.ValidationMessageFor(model => model.SaleReportType, "Required", new { @class = "text-danger" })
                            <label class="text-danger" id="SaleReportTypeErr" style="color:#a94442;font-weight: normal;">Required</label>
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            <label class="control-label erplabel" for="email">Starting Date</label>
                            @Html.EditorFor(model => model.FromDate, new { htmlAttributes = new { @class = "form-control", @required = "required", @id = "FromDate" } })
                            @Html.ValidationMessageFor(model => model.FromDate, "Required", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-2">
                        <div class="form-group">
                            <label class="control-label erplabel" for="email">Last Date</label>
                            @Html.EditorFor(model => model.ToDate, new { htmlAttributes = new { @class = "form-control", @required = "required", @id = "ToDate" } })
                            @Html.ValidationMessageFor(model => model.ToDate, "Required", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="col-lg-4" style="margin: 18px 0 0 0;">
                        <button type="submit" class="btn btn-info" id="Search">Search</button>
                        <button type="submit" class="btn btn-info" id="Print">Print</button>
                        <button class="btn btn-info" onclick="tablesToExcel('testTable', 'Survey Report')">Export to Excel</button>
                        <a class="btn btn-info" href="@Url.Action("Index","SaleReport")"><i class="fa fa-refresh"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="row col-md-12" id="ItemListView">
        @Html.Partial("_InvoiceList")
    </div>
</section>

<script src="~/Scripts/jquery-1.10.2.js" type="text/javascript"></script>
<script src="~/Scripts/jquery.validate.js" type="text/javascript"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#SaleReportTypeErr").hide();
        $("#Search").click(function () {
            var Err = 0;
            var ToDate = $("#ToDate").val();
            var FromDate = $("#FromDate").val();
            var SaleReportType = $("#SaleReportType").val();
            if (SaleReportType == 0) {
                $("#SaleReportTypeErr").show();
                setTimeout(function () {
                    $('#SaleReportTypeErr').fadeOut();
                }, 5000);
                Err++;
            }
            if (Err == 0) {
                var model = {
                    'FromDate': FromDate, 'ToDate': ToDate, 'SaleReportType': SaleReportType
                };
                showProgress();
                $.ajax({
                    type: "Post",
                    url: '@Url.Action("_InvoiceList", "SaleReport")',
                    data: { 'ViewModel': model },
                    dataType: "html",
                    success: function (result) {
                        $("#ItemListView").html(result);
                        hideProgress()
                    },
                    error: function (data) {
                        alert("error");
                    }
                });
            }
        });

        $("#Print").click(function () {
            var Err = 0;
            var ToDate = $("#ToDate").val();
            var FromDate = $("#FromDate").val();
            var Search = $("#KeyWord").val();
            var SaleReportType = $("#SaleReportType").val();
            if (SaleReportType == 0) {
                $("#SaleReportTypeErr").show();
                setTimeout(function () {
                    $('#SaleReportTypeErr').fadeOut();
                }, 5000);
                Err++;
            }
            if (Err == 0) {
                var model = {
                    'FromDate': FromDate, 'ToDate': ToDate, 'SaleReportType': SaleReportType
                };
                showProgress();
                $.ajax({
                    type: "Post",
                    url: '@Url.Action("_InvoiceList", "SaleReport")',
                    data: { 'model': model },
                    dataType: "html",
                    success: function (result) {
                        $("#ItemListView").html(result);
                        hideProgress();
                        Print();
                    },
                    error: function (data) {
                        alert("error");
                    }
                });
            }
        });

        $(function () {
            $("[id*=KeyWord]").autocomplete({
                source: function (request, response) {
                    var Product = new Array();
                    $.ajax({
                        async: false,
                        cache: false,
                        url: "/SaleReport/LedgerList",
                        type: "POST",
                        dataType: "json",
                        data: { Prefix: request.term },
                        success: function (data) {
                            for (var i = 0; i < data.length ; i++) {
                                Product[i] = { label: data[i].Value, Id: data[i].Key, Value: data[i].Key, };
                            }
                        }
                    });
                    response(Product);
                },
                select: function (event, ui) {
                    $("#KeyWord").val(ui.item.label);
                    return false;
                }
            });
        });
    });
    var spinnerVisible = false;
    function showProgress() {
        if (!spinnerVisible) {
            $("div#spinner").fadeIn("fast");
            spinnerVisible = true;
        }
    };
    function hideProgress() {
        if (spinnerVisible) {
            var spinner = $("div#spinner");
            spinner.stop();
            spinner.fadeOut("fast");
            spinnerVisible = false;
        }
    };
    function Print() {
        var printContents = document.getElementById('PrintThis').innerHTML;
        var originalContents = document.body.innerHTML;
        if (navigator.userAgent.toLowerCase().indexOf('chrome') > -1) {
            var popupWin = window.open('', '_blank', 'width=600,height=600,scrollbars=no,menubar=no,toolbar=no,location=no,status=no,titlebar=no');
            popupWin.document.write('<!DOCTYPE html><html><head>' +
                '<link rel="stylesheet" type="text/css" href="style.css" />' +
                '</head><body onload="window.print()"><div class="reward-body">' + printContents + '</div></html>');
            popupWin.onbeforeunload = function (event) {
                popupWin.close();
                return '.\n';
            };
            popupWin.onabort = function (event) {
                popupWin.document.close();
                popupWin.close();
            }
        } else {
            var popupWin = window.open('', '_blank', 'width=800,height=600');
            popupWin.document.open();
            popupWin.document.write('<html><head><link rel="stylesheet" type="text/css" href="style.css" /></head><body onload="window.print()">' + printContents + '</html>');
            popupWin.document.close();
        }
        popupWin.document.close();
    }
    function tablesToExcel() {
        var tab_text = "<table border='2px'><tr bgcolor='#87AFC6'>";
        var textRange; var j = 0;
        tab = document.getElementById('tbl1'); // id of table


        for (j = 0 ; j < tab.rows.length ; j++) {
            tab_text = tab_text + tab.rows[j].innerHTML + "</tr>";
            //tab_text=tab_text+"</tr>";
        }

        tab_text = tab_text + "</table>";
        var ua = window.navigator.userAgent;
        var msie = ua.indexOf("MSIE ");

        if (msie > 0 || !!navigator.userAgent.match(/Trident.*rv\:11\./))      // If Internet Explorer
        {
            txtArea1.document.open("txt/html", "replace");
            txtArea1.document.write(tab_text);
            txtArea1.document.close();
            txtArea1.focus();
            sa = txtArea1.document.execCommand("SaveAs", true, "Say Thanks to Sumit.xls");
        }
        else                 //other browser not tested on IE 11
            sa = window.open('data:application/vnd.ms-excel,' + encodeURIComponent(tab_text));


        return (sa);
    }

</script>

ERP System/Views/SaleReport/_InvoiceList.cshtml
@model DataLayer.ViewModels.PurchaseReportViewModel
@{
    ViewBag.Title = "_ItemList";
}

<div class="box box-primary">
    <div style="width:90%;margin:0 auto;height:auto;margin: 33px auto 0px;" id="PrintThis">
        <div style="width:100%;margin:0 auto;border: 1px solid #000;">
            <center>
                <p style="font-size:18px;text-transform:uppercase;margin: 0 0 0px;">
                    <b>@Model.Company.Name</b>
                </p>
                <p style="margin: 0 0 0px;">
                    @Model.Branch.BranchName
                </p>
            </center>
            <center>
                @Model.Company.Address
                @Model.Company.Address1 @Model.Company.PINCode , Mob : @Model.Company.MobileNo<br>
                GST No : @Model.Company.GST&nbsp;&nbsp;&&nbsp;&nbsp;PAN No :@Model.Company.PANCard
                <div class="time" style="width:100%;border-bottom:1px solid #000;border-top:1px solid #000;margin: 0px 0 0 0;    font-weight: bold;">

                    Sale Report
                    @if (Model.FromDate != null)
                    { <span> From @Model.FromDate.Value.ToString("dd'/'MM'/'yyyy") </span>}
                    @if (Model.ToDate != null)
                    { <span> To @Model.ToDate.Value.ToString("dd'/'MM'/'yyyy") </span>}

                </div>

            </center>

            @if (Model.PurchaseReportList != null && Model.PurchaseReportList.Count > 0)
            {
                <table class="table table-bordered" style="border-collapse:collapse" id="tbl1">
                    <thead>
                        <tr>
                            <th class="erplabel" style="border: 1px solid #000;">SR NO.</th>
                            <th class="erplabel" style="border: 1px solid #000;">Invoice Number</th>
                            <th class="erplabel" style="border: 1px solid #000;">Invoicing Date</th>
                            <th class="erplabel" style="border: 1px solid #000;">No. Of Item</th>
                            <th class="erplabel" style="border: 1px solid #000;">Gross Amount</th>
                            <th class="erplabel" style="border: 1px solid #000;">Total tax</th>
                            <th class="erplabel" style="border: 1px solid #000;">Adjustment</th>
                            <th class="erplabel" style="border: 1px solid #000;">Total</th>
                            <th class="erplabel" style="border: 1px solid #000;">Type</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.PurchaseReportList.Select((x, i) => new { Data = x, Index = i + 1 }))
                        {
                            <tr>
                                <td style="border: 1px solid #000;">@item.Index</td>
                                <td style="border: 1px solid #000;">
                                    @if (item.Data.Type == DataLayer.Constants.SALE_TYPE_SALE_INVOICE)
                                    {
                                        <a href="@Url.Action("Create","SaleInvoice")?id=@item.Data.InvoiceId" style="text-decoration: none;">
                                            @item.Data.InvoiceNumber
                                        </a>
                                    }
                                    else if (item.Data.Type == DataLayer.Constants.SALE_TYPE_SALE_EXCHANGE)
                                    {
                                        <a href="@Url.Action("Exchange","SalesExchange")?id=@item.Data.InvoiceId" style="text-decoration: none;">
                                            @item.Data.InvoiceNumber
                                        </a>
                                    }
                                    else if (item.Data.Type == DataLayer.Constants.SALE_TYPE_PURCHASE_RETURN)
                                    {
                                        <a href="@Url.Action("Create","PurchaseReturn")?id=@item.Data.InvoiceId" style="text-decoration: none;">
                                            @item.Data.InvoiceNumber
                                        </a>
                                    }
                                    else if (item.Data.Type == DataLayer.Constants.SALE_TYPE_SALE_VOUCHER)
                                    {
                                        <a href="@Url.Action("Create","SaleVoucher")?id=@item.Data.InvoiceId" style="text-decoration: none;">
                                            @item.Data.InvoiceNumber
                                        </a>
                                    }
                                    else if (item.Data.Type == DataLayer.Constants.SALE_TYPE_WPS)
                                    {
                                        <a href="@Url.Action("Create","WSP")?id=@item.Data.InvoiceId" style="text-decoration: none;">
                                            @item.Data.InvoiceNumber
                                        </a>
                                    }
                                    else
                                    {
                                        <a href="@Url.Action("CreateNote", "Notes", new { Type = @item.Data.Type , VoucherNumber = @item.Data.InvoiceNumber })" style="text-decoration: none;"> @item.Data.InvoiceNumber</a>
                                    }
                                </td>
                                <td style="border: 1px solid #000;">@item.Data.EntryDate.Value.ToString("dd'/'MM'/'yyyy")</td>
                                <td style="border: 1px solid #000;">@item.Data.NoOfItem</td>
                                <td style="border: 1px solid #000;">@(item.Data.GrossAmount.ToString("0.00"))</td>
                                <td style="border: 1px solid #000;">@(item.Data.TotalTax.ToString("0.00"))</td>
                                <td style="border: 1px solid #000;">@(item.Data.Adjustment.ToString("0.00"))</td>
                                <td style="border: 1px solid #000;">@(item.Data.TotalWithAdjustment.ToString("0.00"))</td>
                                <td style="border: 1px solid #000;">@item.Data.Type</td>
                            </tr>
                        }
                        <tr>
                            <td style="border: 1px solid #000;" colspan="3"></td>
                            <td style="border: 1px solid #000;"><b>Total :</b></td>
                            <td style="border: 1px solid #000;"><b>@Model.Subtotal.ToString("0.00")</b></td>
                            <td style="border: 1px solid #000;"><b>@Model.TotalTax.ToString("0.00")</b></td>
                            <td style="border: 1px solid #000;"><b>@Model.TotalDiscount.ToString("0.00")</b></td>
                            <td style="border: 1px solid #000;"><b>@Model.GrandTotal.ToString("0.00")</b></td>
                            <td style="border: 1px solid #000;"></td>
                        </tr>
                    </tbody>
                </table>
            }
            else
            {
                <label>No Invoice Items</label>
            }

            <div style="width:100%;display: inline-block;margin: 12px 0 0 0;height: 30px;    font-weight: bold;padding-left:7px;">
                <span> * This is a Computer Generated Document hence no Signature is Required</span>

            </div><br>

        </div>


    </div>
</div>