ERP System/Controllers/ContactController.cs
using DataLayer;
using DataLayer.Utils;
using DataLayer.Models;
using System.Collections.Generic;
using System.Web.Mvc;
using DataLayer.ViewModels;
using Microsoft.Ajax.Utilities;
using System.Linq;
using ERP_System.Utils;
using System;

namespace ERP_System.Controllers
{
    [CheckSession]
    public class ContactController : Controller
    {
        ContactHandler handler = new ContactHandler();
        DbConnector db = new DbConnector();
        // GET: Contact
        [RBAC(AccessType = 2)]
        public ActionResult Index(string Type, string ErrorMsg)
        {
            ContactViewModel model = new ContactViewModel();

            if (!string.IsNullOrEmpty(ErrorMsg))
            {
                ViewBag.ErrorMsg = ErrorMsg;
            }

            if (!string.IsNullOrEmpty(Type))
            {
                model.Type = Type;
            }
            else
            {
                model.Type = "Supplier";
            }
            model.ContactList = handler.GetContactList(model.Type);
            return View(model);
        }

        [RBAC(AccessType = 0)]
        public ActionResult Create(string Type, int? id)
        {
            Contact contact = new Contact();
            contact.Type = Type;
            if (id == null)
            {
                contact.Country = "India";               
                contact.Ledger = new Ledger();
                contact.Ledger.EntryDate = DateTime.Now;
                contact.LoginUser = new LoginUser();
                contact.Ledger.ContactSubCategoryList = DropdownManager.GetContactSubCategoryList(null);
            }
            else
            {
                contact = handler.GetContactById(id);
            }
            contact.Ledger.ContactCategoryList = DropdownManager.GetContactCategoryList(null);
            contact.LoginUser.RolesList = DropdownManager.GetRolesList(null);
            contact.DesignationList = DropdownManager.GetDesignationMasterList(null);
            contact.DivisionList = DropdownManager.GetDivisionList(null);
            contact.BranchList = DropdownManager.GetBranchList(null);
            return View(contact);
        }

        [HttpPost]
        public ActionResult Create(Contact contact)
        {
            string errorMessage = handler.CreateContact(contact);
            if(string.IsNullOrEmpty(errorMessage))
            {
                return RedirectToAction("Index", new { Type = contact.Type });
            }
            else
            {
                
            }
            return View(contact);
        }

        public ActionResult _CreateCustomer()
        {
            return View();
        }

        public ActionResult _CreateEmployee()
        {
            return View();
        }

        public ActionResult _CreateSupplier()
        {
            return View();
        }

        public ActionResult _CreateLedger()
        {
            return View();
        }

        public ActionResult _CreateUser()
        {
            return View();
        }

        [HttpPost]
        public ActionResult _ItemList(string Type)
        {                        
            ContactViewModel model = new ContactViewModel();
            model.Type = Type;
            model.ContactList = handler.GetContactList(model.Type);
            return PartialView(model);
        }

        [RBAC(AccessType = 3)]
        public ActionResult Delete(int id, string Type)
        {
            if(id == SessionManager.GetSessionUser().ContactId)
            {
                return RedirectToAction("Index", new { ErrorMsg = "User is Currently Using Software,Cant be Deleted." });
            }
            if (handler.DeleteContact(id))
            {
                return RedirectToAction("Index", new { Type = Type });
            }
            return RedirectToAction("Index", new { ErrorMsg = MessageStore.DeleteError });
        }

        [HttpPost]
        public JsonResult ExistingUser(string UserName)
        {
            DbConnector dbObject = new DbConnector();
            LoginUser model  = dbObject.LoginUsers.Where(x => x.Username == UserName).FirstOrDefault();
            if (model == null)
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            return Json(true, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Details(int id)
        {
            return View();
        }
    }
}

ERP System/Controllers/LeadController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using DataLayer;
using DataLayer.Models;
using DataLayer.ViewModels;
using DataLayer.Utils;
using ERP_System.Utils;

namespace ERP_System.Controllers
{
    [CheckSession]
    public class LeadController : Controller
    {
        LeadViewModel model = new LeadViewModel();
        DbConnector db = new DbConnector();
        // GET: Lead
        public ActionResult Index(string ErrorMsg)
        {
            model.LeadsList = db.GetLeadList();
           

            if (!string.IsNullOrEmpty(ErrorMsg))
            {
                ViewBag.ErrorMsg = ErrorMsg;
            }
            return View(model);
        }

        public ActionResult Create(int? id)
        {
            Lead lead = new Lead();
            if (id.HasValue && id.Value > 0)
            {
                lead = db.Leads.Include("LeadItemList").Where(x => x.LeadId == id).FirstOrDefault();
            }
            else
            {
                lead.Country = "India";
                lead = new Lead();
            }
            lead.ContactList = DropdownManager.GetCustomerForLead();
            return View(lead);
        }

        [HttpPost]
        public ActionResult Create(Lead lead)
        {

            if (ModelState.IsValid)
            {
                //if (lead.City != null)
                //    lead.City = lead.City;
                //else
                //    lead.City = lead.OtherCity.ToString();

               
               
                if (db.SaveLead(lead))
                {
                    List<LeadItem> LeadItemList = SessionManager.GetLeadItemList();
                    foreach(var Item in LeadItemList)
                    {
                        Item.LeadId = lead.LeadId;
                        Item.LeadItemId = 0;
                        db.SaveLeadItem(Item);
                    }
                    SessionManager.EmptySessionList(Constants.LEAD_ITEM_LIST);
                    return RedirectToAction("Index");
                }
            }
            return View(lead);
        }

        [HttpPost]
        public ActionResult Convert(Lead lead)
        {

            if (lead.LeadStatus == "Converted")
            {
                Contact contact = new Contact();
                contact.FirstName = lead.FirstName;
                contact.LastName = lead.LastName;
                contact.Country = lead.Country;
                contact.State = lead.State;
                contact.City = lead.City;
                contact.Email = lead.EmailId;
                contact.Type = "Customer";
                IEnumerable<ModelError> allErrors = ModelState.Values.SelectMany(v => v.Errors);
                db.SaveContact(contact);
            }
            else
            {

            }
            return View(lead);
        }

        public ActionResult Delete(int id)
        {
            Lead lead = db.Leads.Find(id);
            db.RemoveLead(lead);
            if (lead == null)
            {
                return HttpNotFound();
            }
            else
            {
                if (db.RemoveLead(lead))
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Index", new { ErrorMsg = MessageStore.DeleteError });
        }

        public ActionResult CustomerInformation()
        {
            CustomerInformationViewModel model = new CustomerInformationViewModel();
            model.ContactList = DropdownManager.GetCustomerForCRM();
            return View(model);
        }

        [HttpPost]
        public ActionResult CustomerInformation(CustomerInformationViewModel model)
        {
            model.Ledger = db.Ledgers.Where(x => x.LedgerId == model.ContactId).FirstOrDefault();
            model.Contact = model.Ledger.Contact;
            model.SaleInvoiceList = db.SaleInvoices.Where(x => x.CustomerId == model.Ledger.LedgerId).ToList();
            if(model.SaleInvoiceList != null)
            {
                model.TotalSaleValue = model.SaleInvoiceList.Sum(x => x.TotalWithAdjustment);
            }
            model.PurchaseInvoiceList = db.PurchaseInvoices.Where(x => x.AccountId == model.Ledger.LedgerId).ToList();
            if (model.SaleInvoiceList != null)
            {
                model.TotalPurchaseValue = model.PurchaseInvoiceList.Sum(x => x.TotalInvoiceValue.HasValue ? x.TotalInvoiceValue.Value : 0);
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult _LeadItemList(LeadItem model)
        {
            Lead Lead = new Lead();
            if (model.LeadId > 0)
            {
                db.SaveLeadItem(model);
                Lead.LeadItemList = db.LeadItems.Where(x => x.LeadId == model.LeadId).ToList();
            }
            else
            {
                SessionManager.SetLeadItem(model);
                Lead.LeadItemList = SessionManager.GetLeadItemList();
            }
            return PartialView(Lead);
        }

        public ActionResult RemoveLead(int LeadItemId, int LeadId)
        {
            Lead Lead = new Lead();
            if (LeadId > 0)
            {
                LeadItem model = db.LeadItems.Where(x => x.LeadItemId == LeadItemId).FirstOrDefault();
                db.RemoveLeadItem(model);
                Lead.LeadItemList = db.LeadItems.Where(x => x.LeadId == LeadId).ToList();
            }
            else
            {
                SessionManager.RemoveLeadItem(LeadItemId);
                Lead.LeadItemList = SessionManager.GetLeadItemList();
            }
            return PartialView("_LeadItemList", Lead);
        }

        [HttpPost]
        public JsonResult EditLead(int LeadItemId, int LeadId)
        {
            LeadItem model = null;
            if (LeadId > 0)
            {
                model = db.LeadItems.Where(x => x.LeadItemId == LeadItemId).FirstOrDefault();
            }
            else
            {
                model = SessionManager.GetLeadItemList().Where(x => x.LeadItemId == LeadItemId).FirstOrDefault();
            }
            return Json(model);
        }

        [HttpPost]
        public JsonResult GetContact(int ContactId)
        {
            Contact model = db.Contacts.Where(x => x.ContactId == ContactId).FirstOrDefault();
            return Json(model);
        }
    }

}

ERP System/Views/Contact/Create.cshtml
@model DataLayer.Models.Contact
@{
    ViewBag.Title = "User - Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<style>
    .field-validation-valid {
        display: none;
    }

    .validation-summary-valid {
        display: none;
    }
</style>
<script src="~/Scripts/state.js" type="text/javascript"></script>
<script>
    $(document).ready(function () {
        ShowledgerDiv();
        ShowLoginDiv();
        ShowNameField();

        $("#ErrUserName").hide();
        $("#ErrDesignation").hide();
        $("#ErrDivision").hide();
        $("#ErrBranch").hide();

        $("#ContactTitle").change(function () {
            ShowNameField();
        });

        $("#UserName").keyup(function () {
            var UserName = $('#UserName').val();
            $.ajax({
                type: "POST",
                url: '@Url.Action("ExistingUser", "Contact")?UserName=' + UserName,
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: successFunc,
            });
            function successFunc(data) {
                if (data == true) {
                    $("#ErrUserName").show();
                    $("#btnContactSubmit").prop("disabled", true);
                }
                else {
                    $("#btnContactSubmit").prop("disabled", false);
                    $("#ErrUserName").hide();
                }
            }
        });

        $("#ledgerCheck").change(function () {
            ShowledgerDiv()
        });

        $("#loginCheck").change(function () {
            ShowLoginDiv();
        });

        $("#IdType").change(function () {
            $("#IdNumber").val("");            
        });
        
        $("#FirstName,#MiddleName,#LastName,#Country,#State,#City").keypress(function (e) {
            if ((e.which < 97 || e.which > 122) && (e.which < 65 || e.which > 90)) {
                return false;
            }
        });

        $("#PanCardNo").keypress(function (e) {
            if ((e.which < 48 || e.which > 57) && (e.which < 97 || e.which > 122) && (e.which < 65 || e.which > 90)) {
                return false;
            }
            var stat = $(this).val();
            if (stat.length > 9) {
                return false;
            }
        });

        $("#AadharCardNo").keypress(function (e) {
            if ((e.which < 48 || e.which > 57)) {
                return false;
            }
            var stat = $(this).val();
            if (stat.length > 11) {
                return false;
            }
        });

        $("#GSTNo").keypress(function (e) {
            if ((e.which < 48 || e.which > 57) && (e.which < 97 || e.which > 122) && (e.which < 65 || e.which > 90)) {
                return false;
            }
            var stat = $(this).val();
            if (stat.length > 14) {
                return false;
            }
        });

        $("#SalaryPerMonth,#WalletBalance").keypress(function (e) {
            if ((e.which < 48 || e.which > 57) && e.which != 46) {
                return false;
            }
        });

        $("#ContactNo1,#ContactNo2").keypress(function (e) {
            if ((e.which < 48 || e.which > 57)) {
                return false;
            }
            var stat = $(this).val();
            if (stat.length > 9) {
                return false;
            }
        });

        $("#AccountCategoryId").change(function () {
            GetSubcategory();
        });

        $("#btnContactSubmit").click(function () {
            var Error = 0;
            var POB2 = $("#listBox").val();
            document.getElementById('state').value = POB2;

            var POB1 = $("#secondlist").val();
            document.getElementById('City').value = POB1;

            if ($("#loginCheck").is(':checked'))
            {
                if ($("#UserPassword").val() != $("#ConfirmPassword").val())
                {
                    $("#ErrConfirmPassword").show();
                    Error++;
                }
            }
                     
            var RecordType = $("#RecordType").val();
            if (RecordType == "Employee")
            {
                if($("#DesignationId option:selected").val() == "-1")
                {
                    $("#ErrDesignation").show();
                    Error++;
                }

                if($("#DivisionId option:selected").val() == "-1")
                {
                    $("#ErrDivision").show();
                    Error++;
                }

                if ($("#BranchId option:selected").val() == "-1")
                {
                    $("#ErrBranch").show();
                    Error++;
                }
            }
            if(Error > 0)
            {
                return false;
            }
            else
            {
                return true;
            }
        });
    });
    function ShowNameField() {
        var val = $("#ContactTitle option:selected").text();
        if (val == "M/s.") {
            $("#DivFirstName").hide();
            $("#DivMiddleName").hide();
            $("#DivLastName").hide();
            $("#DivCompanyName").show();

        }
        else {
            $("#DivFirstName").show();
            $("#DivMiddleName").show();
            $("#DivLastName").show();
            $("#DivCompanyName").hide();
        }
    }

    function ShowledgerDiv()
    {
        if ($("#ledgerCheck").is(':checked')) {
            $("#ledgerDiv").show();
        }
        else {
            $("#ledgerDiv").hide();
        }
    }

    function ShowLoginDiv()
    {
        if ($("#loginCheck").is(':checked')) {
            $("#loginDiv").show();
            $("#ErrConfirmPassword").hide();
        }
        else {
            $("#loginDiv").hide();
        }
    }

    function GetSubcategory() {
        var value = $("#AccountCategoryId option:selected").val();
        if (value != 0) {
            $("#AccountSubCategory").empty();
            $.ajax({
                type: "Post",
                url: '@Url.Action("ContactSubCategoryList", "Ledger")?contactcategoryid=' + value,
                contentType: "application/json; charset=utf-8",
                dataType: "Json",
                success: function (ContactSubCategoryList) {
                    $("#AccountSubCategory").append('<option value="' + -1 + '">' + "--Select One--" + '</option>');
                    $.each(ContactSubCategoryList, function (i, Sub) {
                        $("#AccountSubCategory").append('<option value="' + Sub.Value + '">' + Sub.Text + '</option>');
                    });
                },
                error: function (data) {
                    alert("error");
                }
            });
        }
    }
</script>

<div style="background-color:lightgray">

    @if (Model.Type == "Employee")
    {
        @Html.Partial("_CreateEmployee", Model)
    }
    else if (Model.Type == "Customer")
    {
        @Html.Partial("_CreateCustomer", Model)
    }
    else if (Model.Type == "Supplier")
    {
        @Html.Partial("_CreateSupplier", Model)
    }
</div>

ERP System/Views/Contact/Details.cshtml
@{
    ViewBag.Title = "Details";
}



<section class="content">

    @using (Html.BeginForm("Create", "Lead", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
     
        <div class="row">
            <div class="col-xs-12 col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Details</h3>
                    </div>
                    <div class="box-body">
                        <div class="col-lg-8 col-md-8 nopadding paddingright">
                            <div class="row">

                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="form-group">
                                        <label class="control-label erplabel" for="email">Title</label><span style="margin: 0px 5px 0 10px;">:</span>
                                        <label class="control-label erplabel" for="email">Abc</label>

                                    </div>
                                </div>

                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                    <div class="form-group">
                                        <label class="control-label erplabel" for="email">First Name</label><span style="margin: 0px 5px 0 10px;">:</span>
                                        <label class="control-label erplabel" for="email">John</label>

                                    </div>
                                </div>

                                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                    <div class="form-group">
                                        <label class="control-label erplabel" for="email">Last Name</label><span style="margin: 0px 5px 0 10px;">:</span>
                                        <label class="control-label erplabel" for="email">Doe</label>


                                    </div>
                                </div>




                            </div>

                            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="form-group">
                                        <label class="control-label erplabel" for="email">Address 1</label><span style="margin: 0px 5px 0 10px;">:</span>
                                        <label class="control-label erplabel" for="email">71 ,Prilgrim Avenue Chevy Chase,Md 20815,44 Shirley Avenue,West Chicago,Philadephia,Pennesylvia 15666 USA</label>

                                    </div>
                                </div>

                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="form-group">
                                        <label class="control-label erplabel" for="email">Address 2</label><span style="margin: 0px 5px 0 10px;">:</span>
                                        <label class="control-label erplabel" for="email">71 ,Prilgrim Avenue Chevy Chase,Md 20815,44 Shirley Avenue,West Chicago,Philadephia,Pennesylvia 15666 USA</label>

                                    </div>
                                </div>




                            </div>

                            <div class="row">


                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="form-group">
                                        <label class="control-label erplabel" for="email">Country</label><span style="margin: 0px 5px 0 10px;">:</span>
                                        <label class="control-label erplabel" for="email">USA</label>
                                    </div>
                                </div>

                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="form-group">
                                        <label class="control-label erplabel" for="email">State</label><span style="margin: 0px 5px 0 10px;">:</span>
                                        <label class="control-label erplabel" for="email">Pennslyavia</label>
                                    </div>
                                </div>




                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="form-group">
                                        <label class="control-label erplabel" for="email">City</label><span style="margin: 0px 5px 0 10px;">:</span>
                                        <label class="control-label erplabel" for="email">Chicago</label>
                                    </div>
                                </div>



                            </div>









                            <div class="row">



                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="form-group">
                                        <label class="control-label erplabel" for="email">Mobile</label><span style="margin: 0px 5px 0 10px;">:</span>
                                        <label class="control-label erplabel" for="email">0123456789</label>
                                    </div>
                                </div>




                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="form-group">
                                        <label class="control-label erplabel" for="email">Phone</label><span style="margin: 0px 5px 0 10px;">:</span>
                                        <label class="control-label erplabel" for="email">0712-758456</label>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="form-group">
                                        <label class="control-label erplabel" for="email">Email</label><span style="margin: 0px 5px 0 10px;">:</span>
                                        <label class="control-label erplabel" for="email">johndoe@gmail.com</label>
                                    </div>
                                </div>

                            </div>

                            <div class="row">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="form-group">
                                        <label class="control-label erplabel" for="email">Pan No.</label><span style="margin: 0px 5px 0 10px;">:</span>
                                        <label class="control-label erplabel" for="email">7451236589</label>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="form-group">
                                        <label class="control-label erplabel" for="email">GST No.</label><span style="margin: 0px 5px 0 10px;">:</span>
                                        <label class="control-label erplabel" for="email">27</label>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="form-group">
                                        <label class="control-label erplabel" for="email">Social ID</label><span style="margin: 0px 5px 0 10px;">:</span>
                                        <label class="control-label erplabel" for="email">444-444-444</label>
                                    </div>
                                </div>





                            </div>
                        </div>


                        <div class="col-lg-4 col-md-4">
                            <div class="row">
                                <div class="box box-primary">
                                    <div class="box-header with-border">
                                        <h3 class="box-title">Details</h3>




                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 nopadding">
                                            <div class="form-group">
                                                <label class="control-label erplabel" for="email">Opening Balance</label><span style="margin: 0px 5px 0 10px;">:</span>
                                                <label class="control-label erplabel" for="email">10,000</label>

                                            </div>
                                        </div>

                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 nopadding">
                                            <div class="form-group">
                                                <label class="control-label erplabel" for="email">Closing Balance</label><span style="margin: 0px 5px 0 10px;">:</span>
                                                <label class="control-label erplabel" for="email">50,000</label>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        </div>

                        <div class="clearfix"></div>
                        <br/>
                <div class="row">
                        <div class="col-lg-8 col-md-8">
                            <div class="box box-primary">
                                <div class="box-header with-border">
                                    <h3 class="box-title">Details</h3>
                                

                                    <div class="tablediv">
                                        <table class="table table-striped">
                                            <thead>
                                                <tr>
                                                    <th>Invoice No.</th>
                                                    <th>Invoice Amount</th>
                                                    <th>Invoice Date</th>
                                                    <th>No. of Item</th>
                                                   
                                                </tr>
                                            </thead>
                                            <tbody></tbody>
                                        </table>

                                    </div>
                                    </div>
                            </div>

                                </div>


                                <div class="col-lg-4 col-md-4 ">
                                    <div class="">
                                        <div class="box box-primary">
                                            <div class="box-header with-border">
                                                <h3 class="box-title">Leads</h3>




                                                <div class="form-group">
                                                    <label class="control-label erplabel" for="email">William</label>
                                                    <label class="control-label erplabel" for="email">10,000</label>
                                                    <label class="control-label erplabel" for="email">Status</label>

                                                </div>

                                               

                                            </div>
                                        </div>
                                    </div>

                                </div>
                        </div>








                                <div class="clearfix"></div>


                            </div>

                        </div>
                </div>
            </div>
      
    }
</section>

ERP System/Views/Contact/_CreateLedger.cshtml
Ledger

ERP System/Views/Contact/_CreateUser.cshtml
User